services:
  app:
    image: ghcr.io/tancred423/naago:latest
    container_name: naago-app
    restart: unless-stopped
    entrypoint: [
      "/bin/bash",
      "-c",
      "deno run --allow-all src/database/migrate.ts && exec deno run --allow-all src/index.ts",
    ]
    volumes:
      - ./image:/app/image:ro
    env_file:
      - .env
    environment:
      IS_PROD: true
    networks:
      - mysql-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mysql-network:
    external: true
    name: mysql-network
